trigger:
  autoCancel: true
  drafts: false
  branches:
    include:
      - main
  paths:
    include:
      - .azure-pipelines
      - "**/*.json"
    exclude:
      - evaluation

pool: MODEL_PERF_TEST_TF

stages:
  - stage: CheckHardware
    jobs:
      - bash: |
          echo "##vso[task.setvariable variable=hardware;]$(jq .hardware xxxx.json)"
          echo "##vso[task.setvariable variable=scripts;]$(jq .scripts xxxx.json)"
        name: setVarFromJsonFileValue

  - stage: Eval
    displayName: Evaluation
    pool: $(hardware)
    dependsOn: [CheckHardware]
    jobs:
      - job:
        steps:
          - template: template/model-template.yml
            parameters:
              scriptsPath: "$(scripts)"
