parameters:
  - name: status
    type: string
    default: "Waiting"
  - name: requestJson
    type: string
    default: ""

steps:
  - task: Bash@3
    inputs:
      filePath: .azure-pipelines/scripts/git_update.sh
    name: gitUpdateStatus${{ parameters.status }}
    env:
      repoURL: $(Build.Repository.Uri)
      requestJson: ${{ parameters.requestJson }}
      commitMessage: "Status update from Azure DevOps"
      status: ${{ parameters.status }}
      TOKEN: $(TOKEN)