parameters:
  - name: scriptsPath
    type: string
    default: "ITREX/cpu"
  - name: requestJson
    type: string
    default: ""
  - name: hardware
    type: string
    default: "gpu"

steps:
  - script: |
      uv pip install -U huggingface_hub[cli]
      git config --global credential.helper store
      huggingface-cli login --token $(HF_TOKEN_MODELS) --add-to-git-credential"
    displayName: Login to huggingface

  - script: |
      npm install -g openclaw@2026.3.24
      uv pip install --no-cache-dir openclaw==2026.3.20
      cp -r openclaw_config/ /root/.openclaw/

      cd ${BUILD_SOURCESDIRECTORY}/
      bash entrypoint.sh
    displayName: Set Up OpenClaw

  - script: |
      cd ${BUILD_SOURCESDIRECTORY}/evaluation/${{ parameters.scriptsPath}}
      # bash run_eval.sh --config_name=${{ parameters.requestJson }}"
      uv pip install git+https://github.com/intel/auto-round.git
      uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cu128
      auto-round --bits 4 --iters 1 --model Qwen/Qwen3-0.6B
    displayName: Eval

  # - template: git-status-template.yml
  #   parameters:
  #     status: "Finished"
  #     requestJson: ${{ parameters.requestJson }}

  # - task: Bash@3
  #   inputs:
  #     filePath: .azure-pipelines/scripts/git_update.sh
  #   name: gitUpdateResults
  #   env:
  #     requestJson: ${{ parameters.requestJson }}
  #     commitMessage: "Commit from Azure DevOps update Results"
  #     status: ""
  #     TOKEN: $(TOKEN)
  #     HUGGINGFACE_TOKEN: $(HUGGINGFACE_TOKEN)
