parameters:
  - name: modelContainerName
    type: string
    default: "model_eval"
  - name: scriptsPath
    type: string
    default: "ITREX/cpu"
  - name: requestJson
    type: string
    default: ""
  - name: hardware
    type: string
    default: "gpu"

steps:
  - script: |
      uv pip install -U huggingface_hub[cli]
      git config --global credential.helper store
      huggingface-cli login --token $(HF_TOKEN_MODELS) --add-to-git-credential"
    displayName: Login to huggingface

  - script: |
      cd ${BUILD_SOURCESDIRECTORY}/evaluation/${{ parameters.scriptsPath}}
      bash run_eval.sh --config_name=${{ parameters.requestJson }}"
    displayName: Eval

  - template: git-status-template.yml
    parameters:
      status: "Finished"
      requestJson: ${{ parameters.requestJson }}

  - task: Bash@3
    inputs:
      filePath: .azure-pipelines/scripts/git_update.sh
    name: gitUpdateResults
    env:
      requestJson: ${{ parameters.requestJson }}
      commitMessage: "Commit from Azure DevOps update Results"
      status: ""
      TOKEN: $(TOKEN)
      HUGGINGFACE_TOKEN: $(HUGGINGFACE_TOKEN)
