steps:
  - script: |
      uv pip install openclaw==2026.3.20
      uv pip install -U huggingface_hub
      cp -r openclaw_config/ /root/.openclaw/

      cd ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/scripts
      python sync_minimax_key.py --token=$(MINIMAX_KEY) --path=/root/.openclaw/agents/main/agent/auth-profiles.json
    displayName: Set Up OpenClaw

  - script: |
      cd ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/scripts
      python update_config_env.py \
        --output ${BUILD_SOURCESDIRECTORY}/$(SCRIPTS_PATH)/config.env \
        --set HTTP_PROXY="" \
        --set HTTPS_PROXY="" \
        --set HF_TOKENS=$(HUGGINGFACE_TOKEN) \
        --set MINIMAX_API_KEY=$(MINIMAX_KEY) \
        --set GIT_TOKEN=$(GIT_TOKEN) \
        --set LB_STORAGE_BLOB_TOKEN=$(LB_STORAGE_BLOB_TOKEN)
    displayName: Update Config

  - script: |
      set -xe
      cd ${BUILD_SOURCESDIRECTORY}/$(SCRIPTS_PATH)
      bash auto.sh $(REQUEST_JSON)
    displayName: Eval
