parameters:
  - name: modelContainerName
    type: string
    default: "model_eval"
  - name: scriptsPath
    type: string
    default: "ITREX/cpu"
  - name: requestJson
    type: string
    default: ""


steps:
  - template: docker-template.yml
    parameters:
      scriptsPath: ${{ parameters.scriptsPath}}

  - script: |
      docker exec ${{ parameters.modelContainerName }} \
        bash -c "cd /lb_eval/evaluation/${{ parameters.scriptsPath}} && bash run_eval.sh --config_name=${{ parameters.requestJson }}"
    displayName: Eval

  - template: git-status-template.yml
    parameters:
      status: "Finished"
      requestJson: ${{ parameters.requestJson }}

  - task: Bash@3
    condition: always()
    inputs:
      targetType: "inline"
      script: |
        docker exec ${{ parameters.modelContainerName }} bash -c "rm -fr /lb_eval/* && rm -fr /lb_eval/.* || true"
    displayName: "Docker clean up"
