trigger:
  paths:
    include:
      - .azure-pipelines
      - "**/*.json"
    exclude:
      - evaluation

pool: $(hardware)

stages:
  - stage: Eval
    displayName: Evaluation
    jobs:
      - job: Eval
        steps:
          # - template: template/model-template.yml
          #   parameters:
          #     scriptsPath: "$(scripts_path)"
          - task: UsePythonVersion@0
            displayName: "Use Python 3.10"
            inputs:
              versionSpec: "3.10"
          - bash: |
              echo "$(scripts_path)"
              echo "$(config)"
              echo "$(hardware)"
              python ${BUILD_SOURCESDIRECTORY}/evaluation/ITREX/cpu/test.py  --config="$(config)"
