trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .azure-pipelines
      - requests
    exclude:
      - evaluation

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: CheckHardware
    jobs:
      - job: CheckHardware
        steps:
        - bash: |
            cd requests
            request_json=$(find . -name *.json)
            hardware=$(grep "hardware" ${request_json} | cut -d'"' -f4)
            scripts=$(grep "scripts" ${request_json} | cut -d'"' -f4)
            if [[ ${hardware} = 'cpu' ]]; then 
                agent_pool='test'
            elif [[ ${hardware} = 'gaudi2' ]]; then
                agent_pool='gaudi2'
            elif [[ ${hardware} = 'gpu' ]]; then
                agent_pool='gpu'
            else
                echo "Hardware not supported"
                exit 1
            fi
            echo "##vso[task.setvariable variable=hardware;isOutput=true]${hardware}"
            echo "##vso[task.setvariable variable=scripts;isOutput=true]${scripts}"
            echo "##vso[task.setvariable variable=agent_pool;isOutput=true]${agent_pool}"
            echo "##vso[task.setvariable variable=request_json;isOutput=true]${request_json}"
          name: setVarFromJsonFileValue
        - bash: |
            echo "Hardware: $(setVarFromJsonFileValue.hardware)"
            echo "Scripts: $(setVarFromJsonFileValue.scripts)"
            echo "Agent Pool: $(setVarFromJsonFileValue.agent_pool)"
            echo "Request Json: $(setVarFromJsonFileValue.request_json)"
        - template: template/git-status-template.yml
          parameters:
            status: "Waiting"


  - stage: Eval
    displayName: Evaluation
    variables:
      hardware: $[stageDependencies.CheckHardware.CheckHardware.outputs['setVarFromJsonFileValue.hardware']]
      scripts: $[stageDependencies.CheckHardware.CheckHardware.outputs['setVarFromJsonFileValue.scripts']]
      agent_pool: $[stageDependencies.CheckHardware.CheckHardware.outputs['setVarFromJsonFileValue.agent_pool']]
    pool: $(agent_pool)
    dependsOn: [CheckHardware]
    jobs:
      - job: Eval
        steps:
          - template: template/model-template.yml
            parameters:
              scriptsPath: "$(scripts)/$(hardware)"
          - template: template/git-status-template.yml
            parameters:
              status: "Finished"
