trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .azure-pipelines
      - "**/*.json"
    exclude:
      - evaluation

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: CheckHardware
    jobs:
      - job: CheckHardware
        steps:
        - bash: |
            echo "##vso[task.setvariable variable=hardware;isOutput=true]$(grep "hardware" requests/*/*.json | cut -d'"' -f4)"
            echo "##vso[task.setvariable variable=scripts;isOutput=true]$(grep "scripts" requests/*/*.json | cut -d'"' -f4)"
          name: setVarFromJsonFileValue
        - bash: |
            echo "Hardware: $(setVarFromJsonFileValue.hardware)"
            echo "Scripts: $(setVarFromJsonFileValue.scripts)"
        - bash: |
            git clone https://github.com/XuehaoSun/lb_eval.git lb_eval_backup
            git checkout ${GITHUB_REF##*/}
            cd lb_eval_backup
            echo "Waiting" > status.txt
            git config --global user.email "xuehao.sun@intel.com"
            git config --global user.name "Sun,Xuehao"
            git remote set-url origin https://XuehaoSun:$(TOKEN)@github.com/XuehaoSun/lb_eval.git
            git add . && git commit -m "Update status" && git push
            rm -rf lb_eval_backup

  - stage: Eval
    displayName: Evaluation
    variables:
      hardware: $[stageDependencies.CheckHardware.CheckHardware.outputs['setVarFromJsonFileValue.hardware']]
      scripts: $[stageDependencies.CheckHardware.CheckHardware.outputs['setVarFromJsonFileValue.scripts']]
    pool: $(hardware)
    dependsOn: [CheckHardware]
    jobs:
      - job: Eval
        steps:
          - template: template/model-template.yml
            parameters:
              scriptsPath: "$(scripts)/$(hardware)"
