trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .azure-pipelines
      - "**/*.json"
    exclude:
      - evaluation

pool: "ICX-16C"

stages:
  - stage: CheckHardware
    jobs:
      - job: CheckHardware
        steps:
        - bash: |
            echo "##vso[task.setvariable variable=hardware;]$(sed -n '1p' eval.txt)"
            echo "##vso[task.setvariable variable=scripts;]$(sed -n '2p' eval.txt)"
          name: setVarFromJsonFileValue

  - stage: Eval
    displayName: Evaluation
    pool: $(hardware)
    dependsOn: [CheckHardware]
    jobs:
      - job: Eval
        steps:
          - template: template/model-template.yml
            parameters:
              scriptsPath: "$(scripts)"
