trigger:
  paths:
    include:
      - .azure-pipelines
      - "**/*.json"
    exclude:
      - evaluation

pool: $(hardware)

stages:
  - stage: Eval
    displayName: Evaluation
    jobs:
      - job: Eval
        steps:
          - template: template/model-template.yml
            parameters:
              scriptsPath: "$(scripts_path)"
